/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Cat API
 * ![cat-api-logo](https://thecatapi.com/_app/immutable/assets/thecatapi-logo.78868573.svg)

## An open, free, read & write API all about Cats
The Cat API gives you access to 10000's of Cat images, and breeds.
- Upload your own Images
- Get detailed info on all Cat Breeds
- Allow your Users to Favourite or Vote on Images
- Save a custom value with each request so you can match data to your Users

## How do i get access?
Just sign up for an API Key from https://thecatapi.com for free. We're looking forward to seeing what you build!
Don't forget to checkout it's sister API - TheDogAPI.com
 * OpenAPI spec version: 1.6.3
 */
import type {
  GetBreeds200,
  GetBreedsBreedId200,
  GetBreedsBreedIdFacts200,
  GetBreedsBreedIdFactsParams,
  GetBreedsParams,
  GetBreedsSearch200,
  GetBreedsSearchParams,
  GetFacts200,
  GetFavourites200,
  GetImages200,
  GetImagesBkIEhN3pG200,
  GetImagesParams,
  GetVotes200,
  ImagesListSearchOrRandom200,
  ImagesListSearchOrRandomParams,
  PostFavourites200,
  PostFavouritesBody,
  PostImagesImageIdBreedsBody,
  PostImagesUpload201,
  PostImagesUploadBody,
  PostVotes201,
  PostVotesBody,
  PostWebhooks200,
  PostWebhooksBody,
} from './Api.schemas'
import { customInstance } from './custom-instance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Searches or returns Random selection from all approved images. Default is to return RANDOM images, but with an API-Key you can use 'order=DESC' or 'order=ASC' along with the 'page' and 'limit' parameters to paginate through them in the order they were approved.

Pagination-Count, Pagination-Page, and Pagination-Limit headers are present in the response so you know the total number of images that can be paginated through for the passed search filters.
 * @summary /images/search
 */
export const imagesListSearchOrRandom = (
  params?: ImagesListSearchOrRandomParams,
  options?: SecondParameter<typeof customInstance<ImagesListSearchOrRandom200>>
) => {
  return customInstance<ImagesListSearchOrRandom200>(
    { url: `/images/search`, method: 'GET', params },
    options
  )
}

/**
 * Get the raw analysis results for any uploaded image
 * @summary /images/:image_id/analysis
 */
export const getImagesBkIEhN3pG = (
  options?: SecondParameter<typeof customInstance<GetImagesBkIEhN3pG200>>
) => {
  return customInstance<GetImagesBkIEhN3pG200>(
    { url: `/images/BkIEhN3pG`, method: 'GET' },
    options
  )
}

/**
 * Only returns images from your account, uploaded via 'api/v1/images/upload'
 * @summary /images/ (Your uploads)
 */
export const getImages = (
  params?: GetImagesParams,
  options?: SecondParameter<typeof customInstance<GetImages200>>
) => {
  return customInstance<GetImages200>(
    { url: `/images/`, method: 'GET', params },
    options
  )
}

/**
 * Make sure you're using the right field to send the image, and Content-Type header
 * @summary /images/upload
 */
export const postImagesUpload = (
  postImagesUploadBody: PostImagesUploadBody,
  options?: SecondParameter<typeof customInstance<PostImagesUpload201>>
) => {
  const formData = new FormData()
  if (postImagesUploadBody.file !== undefined) {
    formData.append(`file`, postImagesUploadBody.file)
  }
  if (postImagesUploadBody.sub_id !== undefined) {
    formData.append(`sub_id`, postImagesUploadBody.sub_id)
  }
  if (postImagesUploadBody.breed_ids !== undefined) {
    formData.append(`breed_ids`, postImagesUploadBody.breed_ids)
  }

  return customInstance<PostImagesUpload201>(
    { url: `/images/upload`, method: 'POST', data: formData },
    options
  )
}

/**
 * @summary /images/:image_id
 */
export const deleteImagesImageId = (
  imageId: string,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    { url: `/images/${imageId}`, method: 'DELETE' },
    options
  )
}

/**
 * @summary /images/:image_id/breeds
 */
export const getImagesImageIdBreeds = (
  imageId: string,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    { url: `/images/${imageId}/breeds`, method: 'GET' },
    options
  )
}

/**
 * @summary /images/:image_id/breeds
 */
export const postImagesImageIdBreeds = (
  imageId: string,
  postImagesImageIdBreedsBody: PostImagesImageIdBreedsBody,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    {
      url: `/images/${imageId}/breeds`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postImagesImageIdBreedsBody,
    },
    options
  )
}

/**
 * @summary /images/:image_id/breeds/:breed_id
 */
export const deleteImagesImageIdBreedsBreedId = (
  imageId: string,
  breedId: string,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    { url: `/images/${imageId}/breeds/${breedId}`, method: 'DELETE' },
    options
  )
}

/**
 * @summary /breeds
 */
export const getBreeds = (
  params?: GetBreedsParams,
  options?: SecondParameter<typeof customInstance<GetBreeds200>>
) => {
  return customInstance<GetBreeds200>(
    { url: `/breeds`, method: 'GET', params },
    options
  )
}

/**
 * @summary /breeds/:breed_id
 */
export const getBreedsBreedId = (
  breedId: string,
  options?: SecondParameter<typeof customInstance<GetBreedsBreedId200>>
) => {
  return customInstance<GetBreedsBreedId200>(
    { url: `/breeds/${breedId}`, method: 'GET' },
    options
  )
}

/**
 * Get one or more facts about the Species. For more at a time just update the 'limit' field, and to paginate through them just increment the 'page' field.

The response headers have the pagination details, such as how many there are in total, what page you're on, and the current amount per page.

To redorder change the order to ASC for ascending order, DESC for descending, and RAND for random order.
 * @summary Get Ordered Fact(s) About Breed
 */
export const getBreedsBreedIdFacts = (
  breedId: string,
  params?: GetBreedsBreedIdFactsParams,
  options?: SecondParameter<typeof customInstance<GetBreedsBreedIdFacts200>>
) => {
  return customInstance<GetBreedsBreedIdFacts200>(
    { url: `/breeds/${breedId}/facts`, method: 'GET', params },
    options
  )
}

/**
 * @summary Search Breeds
 */
export const getBreedsSearch = (
  params?: GetBreedsSearchParams,
  options?: SecondParameter<typeof customInstance<GetBreedsSearch200>>
) => {
  return customInstance<GetBreedsSearch200>(
    { url: `/breeds/search`, method: 'GET', params },
    options
  )
}

/**
 * @summary /favourites
 */
export const getFavourites = (
  options?: SecondParameter<typeof customInstance<GetFavourites200>>
) => {
  return customInstance<GetFavourites200>(
    { url: `/favourites`, method: 'GET' },
    options
  )
}

/**
 * @summary /favourites
 */
export const postFavourites = (
  postFavouritesBody: PostFavouritesBody,
  options?: SecondParameter<typeof customInstance<PostFavourites200>>
) => {
  return customInstance<PostFavourites200>(
    {
      url: `/favourites`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postFavouritesBody,
    },
    options
  )
}

/**
 * @summary /favourites/:favourite_id
 */
export const getFavouritesFavouriteId = (
  favouriteId: string,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    { url: `/favourites/${favouriteId}`, method: 'GET' },
    options
  )
}

/**
 * @summary /favourites/:favourite_id
 */
export const deleteFavouritesFavouriteId = (
  favouriteId: string,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    { url: `/favourites/${favouriteId}`, method: 'DELETE' },
    options
  )
}

/**
 * @summary /votes
 */
export const getVotes = (
  options?: SecondParameter<typeof customInstance<GetVotes200>>
) => {
  return customInstance<GetVotes200>({ url: `/votes`, method: 'GET' }, options)
}

/**
 * @summary /votes
 */
export const postVotes = (
  postVotesBody: PostVotesBody,
  options?: SecondParameter<typeof customInstance<PostVotes201>>
) => {
  return customInstance<PostVotes201>(
    {
      url: `/votes`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postVotesBody,
    },
    options
  )
}

/**
 * @summary /votes/:vote_id
 */
export const getVotesVoteId = (
  voteId: string,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    { url: `/votes/${voteId}`, method: 'GET' },
    options
  )
}

/**
 * @summary /votes/:vote_id
 */
export const deleteVoteVoteId = (
  voteId: string,
  options?: SecondParameter<typeof customInstance<unknown>>
) => {
  return customInstance<unknown>(
    { url: `/vote/${voteId}`, method: 'DELETE' },
    options
  )
}

/**
 * @summary Create Webhook
 */
export const postWebhooks = (
  postWebhooksBody: PostWebhooksBody,
  options?: SecondParameter<typeof customInstance<PostWebhooks200>>
) => {
  return customInstance<PostWebhooks200>(
    {
      url: `/webhooks`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: postWebhooksBody,
    },
    options
  )
}

/**
 * Get one or more Random facts and the Species. For more at a time just update the 'limit' field
 * @summary Get Random Fact(s)
 */
export const getFacts = (
  options?: SecondParameter<typeof customInstance<GetFacts200>>
) => {
  return customInstance<GetFacts200>({ url: `/facts`, method: 'GET' }, options)
}

export type ImagesListSearchOrRandomResult = NonNullable<
  Awaited<ReturnType<typeof imagesListSearchOrRandom>>
>
export type GetImagesBkIEhN3pGResult = NonNullable<
  Awaited<ReturnType<typeof getImagesBkIEhN3pG>>
>
export type GetImagesResult = NonNullable<Awaited<ReturnType<typeof getImages>>>
export type PostImagesUploadResult = NonNullable<
  Awaited<ReturnType<typeof postImagesUpload>>
>
export type DeleteImagesImageIdResult = NonNullable<
  Awaited<ReturnType<typeof deleteImagesImageId>>
>
export type GetImagesImageIdBreedsResult = NonNullable<
  Awaited<ReturnType<typeof getImagesImageIdBreeds>>
>
export type PostImagesImageIdBreedsResult = NonNullable<
  Awaited<ReturnType<typeof postImagesImageIdBreeds>>
>
export type DeleteImagesImageIdBreedsBreedIdResult = NonNullable<
  Awaited<ReturnType<typeof deleteImagesImageIdBreedsBreedId>>
>
export type GetBreedsResult = NonNullable<Awaited<ReturnType<typeof getBreeds>>>
export type GetBreedsBreedIdResult = NonNullable<
  Awaited<ReturnType<typeof getBreedsBreedId>>
>
export type GetBreedsBreedIdFactsResult = NonNullable<
  Awaited<ReturnType<typeof getBreedsBreedIdFacts>>
>
export type GetBreedsSearchResult = NonNullable<
  Awaited<ReturnType<typeof getBreedsSearch>>
>
export type GetFavouritesResult = NonNullable<
  Awaited<ReturnType<typeof getFavourites>>
>
export type PostFavouritesResult = NonNullable<
  Awaited<ReturnType<typeof postFavourites>>
>
export type GetFavouritesFavouriteIdResult = NonNullable<
  Awaited<ReturnType<typeof getFavouritesFavouriteId>>
>
export type DeleteFavouritesFavouriteIdResult = NonNullable<
  Awaited<ReturnType<typeof deleteFavouritesFavouriteId>>
>
export type GetVotesResult = NonNullable<Awaited<ReturnType<typeof getVotes>>>
export type PostVotesResult = NonNullable<Awaited<ReturnType<typeof postVotes>>>
export type GetVotesVoteIdResult = NonNullable<
  Awaited<ReturnType<typeof getVotesVoteId>>
>
export type DeleteVoteVoteIdResult = NonNullable<
  Awaited<ReturnType<typeof deleteVoteVoteId>>
>
export type PostWebhooksResult = NonNullable<
  Awaited<ReturnType<typeof postWebhooks>>
>
export type GetFactsResult = NonNullable<Awaited<ReturnType<typeof getFacts>>>
