/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Cat API
 * ![cat-api-logo](https://thecatapi.com/_app/immutable/assets/thecatapi-logo.78868573.svg)

## An open, free, read & write API all about Cats
The Cat API gives you access to 10000's of Cat images, and breeds.
- Upload your own Images
- Get detailed info on all Cat Breeds
- Allow your Users to Favourite or Vote on Images
- Save a custom value with each request so you can match data to your Users

## How do i get access?
Just sign up for an API Key from https://thecatapi.com for free. We're looking forward to seeing what you build!
Don't forget to checkout it's sister API - TheDogAPI.com
 * OpenAPI spec version: 1.6.3
 */
export type ImagesListSearchOrRandomParams = {
  /**
   * [optional] thumb , small, med or full - small is perfect for Discord
   */
  size?: string
  /**
   * [optional] a comma separated string of types to return e.g. jpg,png for static, or gif for gifs
   */
  mime_types?: string
  /**
   * [optional] json | src
   */
  format?: string
  /**
   * [optional] - only return images with breed data
   */
  has_breeds?: boolean
  /**
   * [optional] default:RANDOM - RANDOM | ASC | DESC
   */
  order?: string
  /**
   * [optional] paginate through results
   */
  page?: number
  /**
   * [optional] number of results to return, up to 25 with a valid API-Key
   */
  limit?: number
}

export type ImagesListSearchOrRandom200 = ImageItem[]

export type ImagesListSearchOrRandom401 = { [key: string]: unknown }

export type GetImagesBkIEhN3pG200 = { [key: string]: unknown }

export type GetImagesParams = {
  /**
   * [Optional] number of images to return valid  1 to 10 - default: 1
   */
  limit?: number
  /**
   * [Optional] only works if account_id is present to page through your own uploads
   */
  page?: number
  /**
   * [Optional] only works if account_id is present, either ASC or DESC - ascending or descending.
   */
  order?: string
}

export type GetImages200 = { [key: string]: unknown }

export type PostImagesUploadBody = {
  file?: Blob
  /** [optional] - a string you can use to segment your images, e.g. knowing which of your own users uploaded it. */
  sub_id?: string
  /** [optional] comma separated string of breed ids contained in the image */
  breed_ids?: string
}

export type PostImagesUpload201 = { [key: string]: unknown }

export type PostImagesImageIdBreedsBody = { [key: string]: unknown }

export type GetBreedsParams = {
  limit?: number
  page?: number
}

export type GetBreeds200 = { [key: string]: unknown }

export type GetBreedsBreedId200 = { [key: string]: unknown }

export type GetBreedsBreedIdFactsParams = {
  limit?: number
  page?: number
  order?: string
}

export type GetBreedsBreedIdFacts200 = { [key: string]: unknown }

export type GetBreedsSearchParams = {
  /**
   * search term for breed name
   */
  q?: string
  /**
   * [optional] whether to attach the reference_image_id image or not
   */
  attach_image?: number
}
export type ImageFavoriteItem = {
  id: string
  image_id: string
  user_id: string
  sub_id: string
  created_at: string
  image: {
    id: string
    url: string
  }
}
export type ImageItem = {
  id: string
  url: string
  width: number
  height: number
}
export type GetBreedsSearch200 = { [key: string]: unknown }

export type GetFavourites200 = ImageFavoriteItem[]

export type PostFavouritesBody = { [key: string]: unknown }

export type PostFavourites200 = { [key: string]: unknown }

export type GetVotes200 = { [key: string]: unknown }

export type PostVotesBody = { [key: string]: unknown }

export type PostVotes201 = { [key: string]: unknown }

export type PostWebhooksBody = { [key: string]: unknown }

export type PostWebhooks200 = { [key: string]: unknown }

export type GetFacts200 = { [key: string]: unknown }
